apiVersion: metrics.aws/v1alpha1
kind: ExternalMetric
metadata:
  name: average-cpu
spec:
  name: average-cpu
  queries:
    - id: expr1m0
      metricStat:
        metric:
          namespace: "ContainerInsights"
          metricName: "pod_cpu_utilization"
        period: 10
        stat: Average
        unit: Percent
      returnData: true
